[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "astro-hej-rts"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
bevy = "0.14.2"
bevy_rapier2d = {version = "0.27.0", features = ["wasm-bindgen"]}
rand = "0.8.5"
wasm-bindgen = "0.2"
web-sys = "0.3.67"
